### ISSUE TITLE
Cannot Rent an office at any station

### ISSUE THREAD

**Issue by DeerHunt3r** [EvEmu-Project/evemu_Crucible#105] opened 2021-04-26 00:57 UTC
**Describe the bug**
While trying to rent a Corp. Office at a station nothing happens,  Moneys are deducted from your wallet.

See Error from Server Below.  Looks like SQL error for Names in the STAOFFICES table. in **BOLD** below.

**To Reproduce**
1. From Within a station and as the CEO of a Corp,  press the Rent office button
2. The warning page displays 
3. Click yes
4. Money is deducted but no office is rented.

**Expected behavior**
I expect to rent an office.

**Screenshots**

**System Details (please complete the following information):**
 - Server OS: [. Ubuntu 20.04 Server
 - Docker 
 - EVEmu Version

**Additional context**

server_1  | 00:48:39 [Bound] CorpStationMgrIMBound::GetQuoteForRentingAnOffice()
server_1  | 00:48:40 [Bound] CorpStationMgrIMBound::RentOffice()
server_1  | 00:48:40 [AcctTrace] TranserFunds() - from: 98000000, to: 1000169, entry: 13, refID: 0, amount: 10000.00, fKey: 1000, tKey: 1000
server_1  | 00:48:40 [AcctTrace] HandleCorpTransaction() - corp: 98000000, from: 98000000, to: 1000169, entry: 13, refID: 0, amount: -10000.00, key: 1000, currency: 0
server_1  | 00:48:40 [DB Error] DoQuery_locked(/src/src/eve-core/database/dbcore.cpp:320): DBCore - Status != Connected
server_1  | 00:48:40 [DB Msg] DBCore error detected.  Look for error msgs in logs prior to this point.
server_1  | 00:48:40 [DB Msg] DBCore attempting to recover...
server_1  | 00:48:40 C           DB User:  evemu
server_1  | 00:48:40 C          DataBase:  evemu
server_1  | 00:48:40 C         DB Server:  db:3306
server_1  | 00:48:40 C     Connect Flags:  2
server_1  | 00:48:40 G  DataBase Manager: DataBase AutoReconnect Enabled
server_1  | 00:48:40 B  DataBase Manager: DataBase Connected
server_1  | 00:48:40 C  DataBase Manager: DataBase Character set: utf8
server_1  | 00:48:40 [DB Msg] DBCore recovery successful.  Continuing.
server_1  | 00:48:41 [Data Error] Name not found for corp 1000169
server_1  | 00:48:41 [AcctTrace] TranserFunds() - toID: Undefined - WIP(1000169) is neither player nor player corp.  Not sending update.
**server_1  | 00:48:41 [DB Error] DoQuery_locked(/src/src/eve-core/database/dbcore.cpp:345): DBCore Query - #1364 in 'INSERT INTO staOffices (corporationID, stationID, officeFolderID, flag, solarSystemID, typeID, stationTypeID, lockDown, rentalFee, expiryDateTime) VALUES (98000000,60014719,66014719,71,30005305, 27, 57,0,10000,132664637210000000)': Field 'name' doesn't have a default value
server_1  | 00:48:41 [DB Error] CreateOffice(/src/src/eve-server/station/StationDB.cpp:27): Error in CreateOffice query: Field 'name' doesn't have a default value
server_1  | 00:48:41 [CorpError] Handle_RentOffice(/src/src/eve-server/corporation/CorpStationMgr.cpp:261): Elsa Coldfist: Error at renting a new office**
server_1  | 00:48:41 [Bound] CorpStationMgrIMBound::GetNumberOfUnrentedOffices()
server_1  | 00:48:51 [Service] charMgr::GetTopBounties()
server_1  | 00:48:51 [DB Error] DoQuery_locked(/src/src/eve-core/database/dbcore.cpp:320): DBCore - Status != Connected
server_1  | 00:48:51 [DB Msg] DBCore error detected.  Look for error msgs in logs prior to this point.
server_1  | 00:48:51 [DB Msg] DBCore attempting to recover...
server_1  | 00:48:51 C           DB User:  evemu
server_1  | 00:48:51 C          DataBase:  evemu
server_1  | 00:48:51 C         DB Server:  db:3306
server_1  | 00:48:51 C     Connect Flags:  2
server_1  | 00:48:51 G  DataBase Manager: DataBase AutoReconnect Enabled
server_1  | 00:48:51 B  DataBase Manager: DataBase Connected
server_1  | 00:48:51 C  DataBase Manager: DataBase Character set: utf8
server_1  | 00:48:51 [DB Msg] DBCore recovery successful.  Continuing.

**Comment by zhyrohaad** [comment] 2021-05-13 14:16
this needs a default value in db *OR* a value in the query.

**Comment by DeerHunt3r** [comment] 2021-06-02 17:19
Ah,  like we did with the AllianceMemberStartDate field in crpCorporation....  I'll setup a new pull request and get it submitted.
Thanks!

**Comment by ToddRosenkrantz** [comment] 2021-06-26 01:28
The problem is that the "OfficeData& odata" object does not have the corporationName and the function:

 uint32 StationDB::CreateOffice(ItemData& idata, OfficeData& odata) does not pass a name field it to dbcore.

I can't determine how to add "crpCorporation.corporationName" to session data (or if it should even be passed that way).

I've created a very ugly & improper 'work around' in StationDB.cpp to test & verify an Office CAN be rented.

uint32 StationDB::CreateOffice(ItemData& idata, OfficeData& odata)
{
    uint32 uid = 0;
    DBerror err;
    if (!sDatabase.RunQueryLID(err, uid,
        "INSERT INTO staOffices (corporationID, stationID, officeFolderID, flag, solarSystemID, typeID, stationTypeID, lockDown, rentalFee, expiryDateTime, name)"
        " VALUES"
        " (%u,%u,%u,%u,%u, 27, %u,%u,%u,%li,(SELECT crpCorporation.corporationName FROM crpCorporation WHERE corporationID = %u))",
        odata.corporationID, odata.stationID, odata.folderID, idata.flag, stDataMgr.GetStationSystemID(odata.stationID), odata.typeID, odata.lockDown, odata.rentalFee, odata.expiryTime, odata.corporationID)
    )
        codelog(DATABASE__ERROR, "Error in CreateOffice query: %s", err.c_str());

    return (odata.officeID = uid);
}


After rebuilding the container, Renting an office opens the Corporate Hanger window with full access.

**Comment by jdhirst** [comment] 2021-09-11 10:48
This has been fixed in 79811ab and will be released into master as part of 0.8.4. Closing this issue.

**Closed by jdhirst** 2021-09-11 10:48 UTC
Labels: needs-triage
