### ISSUE TITLE
Anchoring Structure (POS) causes SEGFAULT

### ISSUE THREAD

**Issue by grenval** [EvEmu-Project/evemu_Crucible#81] opened 2021-04-05 14:11 UTC
**Describe the bug**
Trying to anchor a POS at IPX-H5 VI - Moon 2 
Getting SEGFAULT when clicking 'Anchor Structure'

**To Reproduce**
1. Go to a moon, unsure if it's just in nullsec or all moons and deploy a POS
2. Click on 'Anchor Structure'
5. Profit

**Expected behavior**
Clicking on Anchor Structure should trigger the anchoring placement UI and anchoring timer.

**Screenshots**
Not applicable. 

**System Details (please complete the following information):**
 - Server OS: Ubuntu 20.04 Server
 - Direct build from source
 - EVEmu Version 0.8.3

**Additional context**
gdb stack trace can be found here - https://pastebin.com/dkxsWCnz

**Comment by zhyrohaad** [comment] 2021-04-05 15:37
Structure.cpp:514 is m_destiny->SetPosition(pos);
m_destiny is not set properly for tower.
this will need stepthru to verify.

#2 0x0000555556099617 in DestinyManager::SetPosition (this=0x0, pt=...,
update=false)
at /home/simon/games/evemu_Crucible/src/eve-server/system/DestinyManager.cpp:2317
No locals.
#3 0x0000555555f8baae in StructureSE::SetAnchor (this=0x55555e798200,
pClient=0x5555574b5370, pos=...)
at /home/simon/games/evemu_Crucible/src/eve-server/pos/Structure.cpp:514
dist = 100000
radius = 910000
rad = 1.57079637
updates = std::vector of length 12500, capacity 0 = {
<error reading variable updates (Cannot access memory at address 0x0)>

**Comment by zhyrohaad** [comment] 2021-04-05 15:38
update... i found it.  i missed it after reworking some SE classes
this is a core error.
will need to be updated in tower code.
in this case, we are adding a Destiny object to an OSE, so c'tor/d'tor will have to be put into TowerSE class.
`m_destiny = new Destiny()`  <<< INCOMPLETE...needs more data here
^^^ that needs to be put in `void TowerSE::Init()` in pos/Tower.cpp:145
if anyone wants to try this, then go for it.
if not, i'll fix when i get time.

**Comment by zhyrohaad** [comment] 2021-04-06 22:39
this needs to be tested before i close it....
forgot im not working my own private branch anymore.....

**Comment by SantjagoCorkez** [comment] 2021-08-10 21:50
I've tried to anchor a True Sansha Control Tower at the very dead end of Period Basis. Twice. First time I was still in a noob corp. `Launch for corporation` works. `Anchor` makes the tower object disappear from overview and the player ship makes a warp somewhere to a moon within the system (I wasn't at a moon position this time). I fixed the possible misusage. I created own corp, took another TSCT, ported to the same system, chose a random moon and warped to it. Laucned the tower and clicked `Anchor`. The bug was there again: the tower disappeared from overview and my ship started a warp sequence. I stopped it but that of course didn't fix nothing.

**Comment by SantjagoCorkez** [comment] 2021-08-10 22:58
There's another issue with anchoring control towers:
Right now I have this in my DB (table entity; WHERE typeID = 27786):
```
140000386,True Sansha Control Tower,27786,1000044,30004966,145,0,1,1,-124250877661,23946223864,192979328577,""
140000389,True Sansha Control Tower,27786,98000000,30004966,145,0,1,1,-124250877661,23946223864,192979328577,""
```

See the same XYZ for 2 towers at the same time. That's really impossible state for Retail EVE since there was a restriction:
- a POS can only be anchored at a moon
- only a single POS can be anchored at a moon

I could provide you with more info since I'm a developer. Though I'm not a C++'er and I'm not familiar with the emu code structure. Just tell me where to put a breakpoint and what of a runtime state dump you want me to provide.

What have I found so far:
PosMgr.cpp:663
```c++
    GPoint pos(args.posX, args.posY, args.posZ);
    pTSE->SetAnchor(call.client, pos);
```
Structure.cpp:512 is where a POS is forcibly replaced to by the server. I've found no check for another POS already being in position around the moon.

**Comment by SantjagoCorkez** [comment] 2021-08-10 23:23
Another note:
I'm not sure if that's the correct rule for Crucible but https://wiki.eveuniversity.org/POS_Setup states:
- A corporation that is not a member of an alliance can only anchor a single POS tower per day per system. However, a corporation could anchor multiple POS towers in multiple systems on the same day.
- An alliance can anchor a maximum of (5) POS towers per day per system. Even if there are multiple corporations in the alliance. Just like with the corporate limit, the alliance may anchor more towers in other systems on that day.

I'm not sure if this check must be done at `Launch for corporation` step, there's for sure no such a check at `StructureSE::SetAnchor()`

**Comment by zhyrohaad** [comment] 2021-08-22 17:17
first, i should mention this is not retail eve.  while i've aimed to be as close as i can, there are some things i cannot duplicate, and others that i have fixed or modified because i didnt like how live did it.

as stated in code status, this system is mostly POC, and quite incomplete, even though there are things that work quite well.
that being said, let me touch on your error points and ask for clarification on others...

> .... fixed the possible misusage.....
what 'misusage' are you referring to?

> ....Laucned the tower and clicked `Anchor`. The bug was there again: ....
thats not a bug.

>   ....the tower disappeared from overview and my ship started a warp sequence.......
that is proper operation.  there was a post *somewhere* about towers and how i have them set.
when towers are anchored, they are removed from the moon warp-in point and the moon's warp-in point is changed.
the tower's anchor sequence is started.  the tower sends the anchor coords to the ship, and the ship begins auto warp to the tower's anchor position.  there should be a msg about this once you click "anchor tower".

> .....I stopped it but that of course didn't fix nothing.....
no, it didnt, because there is nothing to 'fix' here.   also, you now cannot access your tower without scanning it down.
that auto-warp is the only way to get the tower's anchor position.   i have code started to make a bookmark, but its incomplete.

>See the same XYZ for 2 towers at the same time. That's really impossible state for Retail EVE since there was a restriction:.....
that's correct.  this is a bug, and is not right.

>  I could provide you with more info since I'm a developer. 
developer of what?   what info are you suggesting to provide?

> ...Structure.cpp:512 is where a POS is forcibly replaced to by the server....
not replaced.  the existing tower is moved.  see partial explanation above.

>  ....I've found no check for another POS already being in position around the moon.....
there are a couple checks thru different systems for anchoring.
look in moon.cpp for tower checks.
there is also code in system boot/load to determine tower count, owners, occupied moons, and few other things relating to POS.
however, as stated previously, this system is quite incomplete.


>    Another note:
I'm not sure if that's the correct rule for Crucible but https://wiki.eveuniversity.org/POS_Setup states:

A corporation that is not a member of an alliance can only anchor a single POS tower per day per system. However, a corporation could anchor multiple POS towers in multiple systems on the same day.
An alliance can anchor a maximum of (5) POS towers per day per system. Even if there are multiple corporations in the alliance. Just like with the corporate limit, the alliance may anchor more towers in other systems on that day.
I'm not sure if this check must be done at Launch for corporation step, there's for sure no such a check at StructureSE::SetAnchor()

i am quite aware of that.
should i mention again that the POS system is POC and rather incomplete?
oh, here's one i havent mentioned yet.....
in my dev code, alliances arent implemented.  even if this check was coded (which it isnt), it would never work.

cheers

**Comment by SantjagoCorkez** [comment] 2021-08-23 17:36
> what 'misusage' are you referring to?

By musisage I ment beeing in a noob corp where I am not (or definitely should be not) assigned a role providing a permit to mess with corps' structures. Though I guess there're no such checks in your code and anyone is still permitted to launch and anchor cosmic structures despite his corp role and permissions. The misusage only referred to original EVE. Don't stick on it yet.

> developer of what? what info are you suggesting to provide?

I'm a software developer and could run the code within debugger, dig through stacks of threads of the server code, could provide some glues on Python since it's my primary spec IRL if you need. Though I'm not familiar with EVE's network protocol and what's the set of packets (and what do their structures look like) but if you need help I could provide you with it.

> there is also code in system boot/load to determine tower count

Since duplicate POSes are still in the DB after several restarts there must be a bug somewhere there. I could try to dig it and maybe propose a PR to fix it. I guess I've started to understand C++ part of the Emu code.

> that is proper operation

I only want to mention that after successfull landing onto warp position for the first `Anchor` try I found that there was no POS in either state in the Bubble. It could be because of disabled system as you explained earlier (and I've successfully landed and anchored a POS in somewhere highsec so that could be a possible explaination).

> oh, here's one i havent mentioned yet.....

I meant nothing like insulting you, sorry if you got that this way. I just want to provide as much of help as I could.

**Comment by zhyrohaad** [comment] 2021-08-24 15:18
> By musisage I ment beeing in a noob corp where I am not (or definitely should be not) assigned a role providing a permit to mess with corps' structures. Though I guess there're no such checks in your code and anyone is still permitted to launch and anchor cosmic structures despite his corp role and permissions. The misusage only referred to original EVE. Don't stick on it yet.

ahhh...i wasnt following your meaning and totally missed the "launch in noob corp" part.  the launch/anchor code *should* be checking roles, but it seems there is an error somewhere (obviously).  i know there is a few things i havent finished, and many loose ends, but i had thought the basic role checks were working.

> I'm a software developer and could run the code within debugger, dig through stacks of threads of the server code, could provide some glues on Python since it's my primary spec IRL if you need. Though I'm not familiar with EVE's network protocol and what's the set of packets (and what do their structures look like) but if you need help I could provide you with it.

ok, that's good to know.  my python is weak (at best).  however, since this (POS) system is incomplete, i'd consider stack tracing a waste of time.....still too many errors/incomplete items in code.
honestly, the bughunting/BT isnt that big a deal...its finding time to actually fix things.


> Since duplicate POSes are still in the DB after several restarts there must be a bug somewhere there. I could try to dig it and maybe propose a PR to fix it. I guess I've started to understand C++ part of the Emu code.

that is definitely a bug.   however, since the code is incomplete, i wouldnt waste time on it, as it should be integrated with other methods that may/may not be coded.  
if you're itching to dig in, then go for it.  it wont be a simple "add check here" type fix, and i dont think i have POS code documented very well, so learning curve will be quite steep. 


> I only want to mention that after successfull landing onto warp position for the first `Anchor` try I found that there was no POS in either state in the Bubble. It could be because of disabled system as you explained earlier (and I've successfully landed and anchored a POS in somewhere highsec so that could be a possible explaination).

you did complete the auto-warp after anchoring a tower?  and the tower wasnt there?  very odd.
while the POS system is incomplete, the parts i had working, were working quite well in my testing.... http://eve.alasiya.net/gallery/POS/

 
> I meant nothing like insulting you, sorry if you got that this way. I just want to provide as much of help as I could.

im probably a bit over-touchy concerning my code.  over the 10+ years i've been coding evemu, i have encountered way too many "this shit dont work!!  fix it!!" messages (not you, ariyna :) ), and 90% of them are known incomplete systems.   its no secret evemu is incomplete, yet many "testers" jump in expecting something remarkably close to Live.   so, yeah, i tend to bite back kinda hard.  this also 'weeds out' the kids that just want shit handed to them and are kinda useless as 'testers'....they'll run away once i bite back.

thank you for elaborating and offering information.

cheers
allan

**Comment by zhyrohaad** [comment] 2021-10-31 06:35
im not able to reproduce this error, after multiple tower anchoring sessions.
closing issue.

**Closed by zhyrohaad** 2021-10-31 06:35 UTC
Labels: to test, touch
