### ISSUE TITLE
Recovering Probes results in server and client crash

### ISSUE THREAD

**Issue by OperationDx** [EvEmu-Project/evemu_Crucible#262] opened 2023-07-31 23:03 UTC
**Describe the bug**
Bug - Recovering Probes results in server and client crash. After the player scans down a cosmic signature. In the scan window you hit the button recover probes. When the first probe reaches the player the Server and client will crash. To be more specific flying the covert ops ship Anathema and trying to recover core probes crashes the system every time.   

**To Reproduce**
Get Covert Ops ship Anathema.
Fit the ship with a probe launcher and install core probe 1's
Launch the probes and scan for cosmic signature.
When done hit the recover probs button in the scan widow.
Server and game should crash.

**Expected behavior**
After hitting the recover probes button in the scan window.
The probes should show up in the players cargo hold.

**Screenshots**
None for this one.

**System Details (please complete the following information):**
 - Server OS: [Ubuntu]
 - Docker - Latest Staging build 0.8.5 as of 7/31/23

**Additional context**
Nothing extra to report.

**Comment by OperationDx** [comment] 2023-07-31 23:28
![2023 07 31 23 27 13](https://github.com/EvEmu-Project/evemu_Crucible/assets/141080303/f62bb319-7299-477a-8e1a-3bde02376bc7)

**Comment by d10sfan** [comment] 2023-09-02 04:18
Related to this: https://github.com/EvEmu-Project/evemu_Crucible/issues/170

Looks like it's because of the erase, maybe because it's happening twice?

**Comment by jdhirst** [comment] 2024-05-03 07:52
Closing as duplicate of #170

**Closed by jdhirst** 2024-05-03 07:52 UTC
Labels: needs-triage
