### ISSUE TITLE
Error loading S charges to 150mm Carbide Railgun I

### ISSUE THREAD

**Issue by matthew1smith** [EvEmu-Project/evemu_Crucible#193] opened 2022-03-20 10:12 UTC
**Describe the bug**
Purchased x3 150mm Carbide Railgun I.  Purchased 550 Antimatter Charge S, Plutonium Charge S, Thorium Charge S, and Uranium Charge S.  Produces error stating charge is the wrong size.

**To Reproduce**
1. Fitted modules to my Cormorant straight from Items.
2. Put each stack of charges into My Cargo.
3. Dragged charges over the top of modules in Fitting window.
4. Error message stated charge was the wrong size.

**Expected behavior**
Charge should load into module without error message.

**Screenshots**

**System Details (please complete the following information):**

- Server OS: Windows 10 using DockerDesktop, GDB active within image, shown as Fedora 10.2-4.fc33
- Docker build
- EVEmu Version 0.8.4 (staging)

**Additional context**
Fixed by attempting following in sequence:
- stripped fitting;
- fitted railguns through right-click -> Fit to Active Ship;
- dragged one stack of Antimatter Charge S into items, then dragged over top of module;
- seemingly fixed, as I could then drag from My Cargo over any of the fitted hybrid turrets.

**Comment by jdhirst** [comment] 2022-03-22 07:13
Good catch! Hmm, so it seems the issue is specific to dragging the items from your cargo to the turrets themselves? In that case, I suggest adding inventory logging to your log.ini and re-attempting this. Maybe we can gather more details on exactly where the failure is at that point.

**Comment by beelitzs** [comment] 2022-03-27 07:30
Not able to replicate this issue in 666a3f9643ea5ea07e6971a3784d0892b282bb60
Dragging small charges into 150mm Carbide Railgun I's loads them as expected (unloading existing charges if present) both in station and while undocked.
Only able to bring up the wrong size error when attempting to load M size or when using Dual 150mm's which is expected.

@sanitybane Any further context to help replicate?

**Comment by sanitybane** [comment] 2022-03-27 14:43
> @sanitybane Any further context to help replicate?

When it occurred, it was with a Cormorant bought off the market from seeding.  Not sure if that goes through different calls from spawn commands yet as I've not got my Linux dev box running.  Have rebuilt source from latest staging but market seeding failed, so couldn't rule out maybe an issue with it being somehow from a seeded ship?  Tried to replicate using a spawned Cormorant and using the GMH 'give me all skills' button in Show Info, but couldn't replicate.

**Comment by jdhirst** [comment] 2024-05-03 07:36
Closing as not reproducible. If it reoccurs, please reopen.

**Closed by jdhirst** 2024-05-03 07:37 UTC
Labels: needs-triage
