### ISSUE TITLE
Tax rate is not using Corp Values.

### ISSUE THREAD

**Issue by DeerHunt3r** [EvEmu-Project/evemu_Crucible#112] opened 2021-05-08 22:54 UTC
**Describe the bug**
Every time you purchase something from the Market you're charged 100% tax 

**To Reproduce**
1. open the market
2. make a purchase
3. open wallet
4. click load
5. notice your purchase and tax charge

**Expected behavior**
I believe the corp tax rate found in the table crpCorporation is supposed to be used.  The default tax rate is 11% but that is not what the system is using.

**Screenshots**
![image](https://user-images.githubusercontent.com/80292862/117555613-3fc43080-b026-11eb-8f37-389200c7c7dc.png)

**System Details (please complete the following information):**
 - Server OS:  Ubuntu 20.04 Server
 - Docker o
 - EVEmu 339f064

**Additional context**
nothing else at this time.

**Comment by DeerHunt3r** [comment] 2021-05-08 23:04
Additionally taxes are being applied incorrectly,  on live the seller pays the taxes.. not the buyer.

**Comment by Almamu** [comment] 2021-05-08 23:28
Small correction on my side, the tax is always 5% on market orders (can be lower based on accounting and tax evasion levels), not based off the corp's tax rate, but the tax has to be applied to the seller, not the buyer as it is right now.

**Comment by Almamu** [comment] 2021-05-09 01:50
Should be fixed on 9a584d81e1d6a5a7683693da6cd9deadbdfd9167, 06dd90bede6317287659f1655da8b78e1b8a7124 and f6ab4407fc6bb37cbadf1ff2ced4817c1d5546e6

**Comment by zhyrohaad** [comment] 2021-05-13 14:25
market rewrite wasnt fully tested, so there are probably more bugs in it like this.

**Comment by Almamu** [comment] 2021-05-13 16:06
So far the only two things that needed a fix was taxing and traders joe id misbehaving with items, the rest seems to be working fine.

**Comment by jdhirst** [comment] 2021-09-06 11:32
Confirmed this as fixed in 0.8.4 staging builds. Closing to prepare for 0.8.4 release.

**Closed by jdhirst** 2021-09-06 11:32 UTC
Labels: to test
