### ISSUE TITLE
Objects not visible to the second ship to arrive at a location already occupied by another pilot.

### ISSUE THREAD

**Issue by jdhirst** [EvEmu-Project/evemu_Crucible#15] opened 2021-04-04 15:09 UTC
From AlasiyaEvE created by [DeerHunt3r](https://github.com/DeerHunt3r): zhyrohaad/AlasiyaEvE#154  

**Describe the bug**
When a ship stops at a location, Asteroid field and a second ship flys to the same field,  the second ship does not see / scan any of the asteroids in that field,  same if there are "bad guys" attacking the first ship,  the second ship does not see the targets or anything at the location

**To Reproduce**
launch 2 accounts
fly one ship to an asteroid field
wait a few seconds,
fly the second ship (from the second account) to the same location

**Expected behavior**
All asteroids, targetable objects should be visible to ALL ships at a location

**Screenshots**

**Additional context**
I am running both accounts from the same computer,  could be thats the issue?  not sure as I only have 1 usable system for both accounts.  at the time I tested this both pilots were teamed.

**Comment by jdhirst** [comment] 2021-04-04 15:09
this was a problem years ago, but was fixed.
somewhere in recent history of updates has caused this to resurface.
i will look into it again, and put rather high on the list.

**Comment by zhyrohaad** [comment] 2021-11-01 13:14
i thought this was addressed/fixed a while back
has anyone else confirmed this is still broken?

**Comment by DeerHunt3r** [comment] 2021-11-02 03:34
Just tested,  pilots can see each other,  but only the first pilot to show up to an asteroid field can see or target the roids..

**Comment by zhyrohaad** [comment] 2021-11-02 11:10
ok, thank you.  i'll look into it more.

**Comment by zhyrohaad** [comment] 2021-11-02 11:56
closing this as dupe of #92 (yes, backwards, but other is by original author)

**Closed by zhyrohaad** 2021-11-02 11:56 UTC
Labels: bug, dev review, in progress
